{% set name = "empyrical" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b197a88cb389b4150272a3d8eacb27e925e52c6bfb14a1c9af02861cbf0fa6e6

build:
  # The package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.2
    - pandas >=0.16.1
    - scipy >=0.15.1
    - pandas-datareader >=0.2

test:
  imports:
    - empyrical
    - empyrical.tests
  requires:
    - nose >=1.3.7
    - parameterized >=0.6.1

about:
  home: https://github.com/quantopian/empyrical
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: empyrical is a Python library with performance and risk statistics commonly used in quantitative finance

  description: |
    empyrical is a Python library with performance and risk
    statistics commonly used in quantitative finance by Quantopian Inc
  dev_url: https://github.com/quantopian/empyrical

extra:
  recipe-maintainers:
    - alen12345
    - fawce
    - gerrymanoim
    - jbredeche
    - jdricklefs
    - llllllllll
    - richafrank
