travis:
  secure:
    BINSTAR_TOKEN: S6tfwqcGQPoU2RjpxS+KzlR5DiuXMUKKjd3rE7lhixiEBd5/h3ad1UR4J4c0QXlsetpawmr8dc21YDpoTwJ87LJ7/C0cG/yPKvZSpxgreh7sEXxlr19TS9zI9xKNhJ5nT2oTtJ2Gjv1cBW5lWClHs4kOUeQufuqDetLKq/HO3N/isihomBZCbiWcYNuBZBGo0lt/Apie5Tht6hAQ+gQYTBO8rikefzMfLu1h1djPnqvCTWvQ2bNzhqVahBWKq+npVHcARC/yBZp0TsK9CjJQ93sIcMYB/SmvBPq48Nz7Ck7Id7i/ck8Op2mPOKyPC90SsIcR954ESp4znlkiSyg15BfM9gRCou4HxhzuwKWKgxR1r+Ms9Wdwh5WIDvOJMzw4vfETeBvuO38tlyxs+diuz+vo2EfJVA71KACZaocO9vh2N4qyGIcDQAdMFDu6+AVlTu5LIl3XHUKt8pvS7fJc4AgaY78wcOdqxsvDoRaWPlRi5J8AuOfKv/ivSwzLHqke9NtW8PnS9j6ksPuhNE087A/3mQUI4KdwDUsCCN/qNBwfkwUkHGcbrfar1JvoywLkKGJM97mEeWZSlFk+QDbvvMczufkQoWqouJC6GK6Ok6N+b50fEvln1Fc+C9b4/3sbxTXHbbiq+HciI6EaEOfKU9k1FyTWk7LtozCOsnLDAGo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
